### PR TITLE
Dynamic FwUid retreival from config

### LINKED ISSUE #4: API is not working
Screen Shot 2020-06-10 at 4 47 42 PM

### LINKED ISSUE #7: Points/Badges/Certification API's not working :(
The Leader board solution was working really well 2 days ago and then it stopped pulling badges and certs etc.  

This endpoint gets an application error.  

https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/jartz1/certifications

but this endpoint seems to workj ust fine:

https://go-trailhead-leaderboard-api.herokuapp.com/trailblazer/jartz1/profile

### PR DESCRIPTION
**Pull request by PaulWeakley**
Using a global variable that will be "refreshed" in the event of a failure and the request will be retried after getting the new fwuid.

Note: if the fwuid is not retrieved successfully then it will not retry the call. should add additional logging to handle the exception case

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -10,15 +11,18 @@ import (
 	"strings"
 	"time"
 
+	"./trailhead"
```
Comment (meruff) [inline main.go]: You'll want to switch this import statement back to `"github.com/meruff/go-trailhead-leaderboard-api/trailhead"` actually, as that's how Golang prefers importing packages.

File: main.go [hunk 2]
```diff
@@ -200,6 +198,59 @@ func getTrailheadID(w http.ResponseWriter, userAlias string) string {
 	return userAlias
 }
 
+func doTrailheadAuraCallout(apexAction string, pageURI string) trailhead.Data {
```
Comment (meruff) [inline main.go:215]: Can you add a description for this method starting with the name of the method? In Golang, you'd do:

```
// doTrailheadAuraCallout calls out to trailhead .... <rest of description>
```

File: main.go [hunk 3]
```diff
@@ -200,6 +198,59 @@ func getTrailheadID(w http.ResponseWriter, userAlias string) string {
...
+		return doTrailheadCallout(
+			`message={"actions":[` + apexAction + `]}` +
+				`&aura.context=` + trailhead.GetAuraContext(auraConfig) + `&aura.pageURI=` + pageURI + `&aura.token="`)
+	}
+
+	return trailhead.Data{Actions: nil}
+}
+
+// Aquire Profile App Config
+func updateAuraProfileAppConfig() {
```
Comment (meruff) [inline main.go:242]: Same here:

```
// updateAuraProfileAppConfig does this...
func updateAuraProfileAppConfig() {
```

Also "Aquire"

File: main.go [hunk 4]
```diff
@@ -200,6 +198,59 @@ func getTrailheadID(w http.ResponseWriter, userAlias string) string {
...
+	//return "axnV2upVY_ZFzdo18txAEw"
```
Comment (meruff) [inline main.go]: Remove commented out code

File: trailhead/trailhead.go [hunk 5]
```diff
@@ -37,11 +35,15 @@ type Data struct {
 	} `json:"context"`
 }
 
+type AuraConfig struct {
```
Comment (meruff) [inline trailhead/trailhead.go]: We'll add a comment here stating what this struct represents like:

```
// AuraConfig represents ....
type AuraConfig struct {
```

File: main.go [hunk 6]
```diff
@@ -200,6 +198,59 @@ func getTrailheadID(w http.ResponseWriter, userAlias string) string {
...
+	url := trailblazerProfileAppConfig
+	method := "GET"
+
+	client := &http.Client{}
+	req, err := http.NewRequest(method, url, nil)
+
+	if err != nil {
+		fmt.Println(err)
```
Comment (meruff) [inline main.go]: Can you switch this to `log.Println()` instead of `fmt` and remove the import? `log` is preferred as it adds timestamps to the logged message automatically, `fmt` does not, example:

```
2020/08/16 14:45:13 [GET] "/trailblazer/matruff/certifications" 2.765204924s
2020/08/16 14:45:19 [GET] "/trailblazer/matruff/badges" 1.401023577s
2020/08/16 14:48:16 [GET] "/trailblazer/matruff/badges/superbadge" 2.030988269s
2020/08/16 14:48:53 [GET] "/trailblazer/matruff" 1.980818238s
```

File: main.go [hunk 7]
```diff
@@ -200,6 +198,59 @@ func getTrailheadID(w http.ResponseWriter, userAlias string) string {
 	return userAlias
 }
 
+func doTrailheadAuraCallout(apexAction string, pageURI string) trailhead.Data {
+	// If config has been retrieved, try aura call
+	if 0 != len(auraConfig.FwUid) {
```
Comment (meruff) [inline main.go]: I was talking with a friend of mine (who knows way more about Go than I do) about handling this and while updating the config for this instance using a global var works locally and probably on the Heroku server, it's not preferred for a server application. I think the problem that could arise is serving multiple instances of the application at once. 

AFAIK, Heroku serves one instance of the application once the dyno is spun up, since the dyno goes to sleep whenever it hasn't been pinged in a while. The way you have this built currently, when the application is first spun up it'll need to get the `fwuid` value from your `updateAuraProfileAppConfig()` method and cache it. All subsequent requests should then reference that value. So in theory, and in my local testing, it works perfectly. 

IMO, this solution should work fine enough for one instance of the application run on Heroku. And even if there were multiple requests, or Go routines, the way this is built would just get the value the first time, so I say we leave this as is for now and see how it works. The only thing I would say we'd think about is on line [208](https://github.com/meruff/go-trailhead-leaderboard-api/pull/9/files#diff-7ddfb3e035b42cd70649cc33393fe32cR208) where it checks if `Actions` is not `nil`. What if `Actions` IS `nil`? We should add an else that would do a callout to `updateAuraProfileAppConfig` to update the `fwuid` value. In this case, the server was up, with a valid `fwuid`, but then that value changed in the middle of the instance so it became invalid, thus a new value is needed again. There's probably a better way to implement that instead of an else with duplicate calls to code, but I'll let you decide if you wanna refactor `doTrailheadAuraCallout` now or just leave it. I can look at it later and see if we can simplify that.

**Review by meruff — CHANGES_REQUESTED** [review]
Overall, this looks really good @PaulWeakley, thanks for submitting this. Let me know if you have any questions on my requested changes. This should solve #4 and #7 for good. At least as far as with what info Trailhead is giving us.

File: main.go (hunk 1 above)
Comment (PaulWeakley) [reply main.go]: Maybe I don't understand the way Go works enough but it seems to me that this would be preferred when the referenced package is not in the same repository. With this approach then you would have to commit/push changes to the trailhead folder first before you could make changes to the main file. In this case, I would need to create a PR for you to pull into your repo before the main file on my machine would even work

File: main.go (hunk 7 above)
Comment (PaulWeakley) [reply main.go]: I agree with you in that a multi-instance container each would have to store this value in memory but it's preferable to a database value since each instance would need the refresh. You'd need a cache layer or a notification system to synchronize the value. The performance hit of this call is low with an immediate recovery. 

With regards to the flow, if the ID is present and the call fails, it won't return and will update the ID and then retry the call. I thought about using recursion instead of duplicating the 3 lines but the duplication prevents an infinite loop bug from ever existing. Would only want to retry once in case there was some other problem. The code will recover as-is if the FwUID changes without the instance having to be restarted. I didn't explicitly use the else because this flow will get the config "just in time" on the first call. So if it exists and fails it will just continue like it was the first call to the instance.

File: main.go (hunk 6 above)
Comment (PaulWeakley) [reply main.go]: Copy and paste "bug" from before your refactor. Easy change, good catch.

**Comment by PaulWeakley** [comment]
I have made the requested modifications except the package reference. It does not work for me to reference the package this way because it only uses the GitHub version of that file. Also resolved the UserID issue that was reported and simplified the Aura Context retrieval to be more flexible with future changes from Salesforce. During testing I noticed that the ProfileApp ID had changed as well so wanted to enhance the context problems.

**Comment by meruff** [comment]
Hey @PaulWeakley. First of all, thanks for all your work on this!! 

When I pull this down and run it locally, I'm not getting data back from Trailhead. I think it may have something to do with the `cuid` and `updateAuraProfileAppConfig` changes. Do all the endpoints return data for you locally? Here's what I found:

When I look at the network tab on my Trailhead profile, I see that the `userId` being used in the request for me is "0051I000004UgTlQAK":

Screen Shot 2020-08-21 at 12 39 56 PM

However, with the new changes to the API, my `cuid` comes back as "0051I000000SUFYQA4", which is a different Id:

image

In this image, the JavaScript that is returned to the page shows a null value for `uid`. But there is a `profileData` var that is present on the page with the "correct" Id. I assume this is "correct" as that's what Trailhead is using to get data on your profile. `cuid` must be some other Id for another one of their internal orgs. 

Screen Shot 2020-08-21 at 12 38 03 PM

Using this Id I'm able to get data back. But in order to do so, I had to revert the `aura.context` request data back to the original way we had it. I think the new context data includes too many attributes and the Trailhead service we're calling out to isn't expecting them, resulting in an error:

image

I think the original method you had that extracted the `fwuid` worked well, maybe we switch back to that? Or only take certain attributes from the aura action response rather than all of them? We could unmarshal them into a new struct for example in the `trailhead` package.

**Comment by meruff** [comment]
As far as the `./trailhead` import. Because this is a github hosted repo, golang sets up your local GOPATH as `go/src/github.com/<githubUserName>/<repo>`. That's why it's expecting the github.com portion in there rather than just using `./trailhead`. I imagine you don't have your go project in the go path so it's not able to find the proper trailhead package file, hence you need to set it to your local pwd. When I push to Heroku, it has the go path set up in github.com format, therefore it works on the server as well. My go path was set up automatically and I created the repo in said path. A bit more info about import paths:

https://golang.org/doc/gopath_code.html#ImportPaths

**Comment by PaulWeakley** [comment]
You're welcome @meruff. It has been a fun/interesting challenge to solve. It was successful when I pushed the code to git but it appears there has been yet another change from the salesforce side. I'll take a look and I agree it probably has to do with the profile app's aura config because I'm getting that same cuid "0051I000000SUFYQA4" for my testing.

**Comment by PaulWeakley** [comment]
Interesting development, the UID/CUID also exists in the browser when using private mode. Something else is going on with this. I'll dig in further this weekend hopefully to find what might be going on with the requests. I was able to check and see that the browser still got the right user id. So I'm guessing there's another call that bridges that gap.

**Comment by PaulWeakley** [comment]
I still had the wrong user Id logic, digging further and comparing between postman and the browser network traffic I believe I found the right one. Found a difference with the URL execute parameter and "partially" reverted the Aura context changes to keep it smaller but still take into account the dynamic components.

**Review by meruff — APPROVED** [review]

**Comment by meruff** [comment]
Thanks for your work on this @PaulWeakley, looks good on my end. I believe this solves #4, #7, and #10. I'll merge it up and push it to my Heroku server.
